version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam

  settings:
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/NCCloud/zap-operator
