// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ZapScan) DeepCopyInto(out *ZapScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	if in.Spec.OpenAPI != nil {
		out.Spec.OpenAPI = new(string)
		*out.Spec.OpenAPI = *in.Spec.OpenAPI
	}
	if in.Spec.JobNamespace != nil {
		out.Spec.JobNamespace = new(string)
		*out.Spec.JobNamespace = *in.Spec.JobNamespace
	}
	if in.Spec.ServiceAccountName != nil {
		out.Spec.ServiceAccountName = new(string)
		*out.Spec.ServiceAccountName = *in.Spec.ServiceAccountName
	}
	if in.Spec.Image != nil {
		out.Spec.Image = new(string)
		*out.Spec.Image = *in.Spec.Image
	}
	if in.Spec.Args != nil {
		out.Spec.Args = append([]string{}, in.Spec.Args...)
	}
	if in.Spec.Cleanup != nil {
		out.Spec.Cleanup = new(bool)
		*out.Spec.Cleanup = *in.Spec.Cleanup
	}
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ZapScan) DeepCopy() *ZapScan {
	if in == nil {
		return nil
	}
	out := new(ZapScan)
	in.DeepCopyInto(out)
	return out
}

func (in *ZapScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZapScanList) DeepCopyInto(out *ZapScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ZapScan, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *ZapScanList) DeepCopy() *ZapScanList {
	if in == nil {
		return nil
	}
	out := new(ZapScanList)
	in.DeepCopyInto(out)
	return out
}

func (in *ZapScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZapScanStatus) DeepCopyInto(out *ZapScanStatus) {
	*out = *in
	if in.StartedAt != nil {
		out.StartedAt = in.StartedAt.DeepCopy()
	}
	if in.FinishedAt != nil {
		out.FinishedAt = in.FinishedAt.DeepCopy()
	}
}

func (in *ZapScanStatus) DeepCopy() *ZapScanStatus {
	if in == nil {
		return nil
	}
	out := new(ZapScanStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ZapScheduledScan) DeepCopyInto(out *ZapScheduledScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	if in.Spec.Suspend != nil {
		out.Spec.Suspend = new(bool)
		*out.Spec.Suspend = *in.Spec.Suspend
	}
	if in.Spec.ConcurrencyPolicy != nil {
		out.Spec.ConcurrencyPolicy = new(string)
		*out.Spec.ConcurrencyPolicy = *in.Spec.ConcurrencyPolicy
	}
	if in.Spec.Template.OpenAPI != nil {
		out.Spec.Template.OpenAPI = new(string)
		*out.Spec.Template.OpenAPI = *in.Spec.Template.OpenAPI
	}
	if in.Spec.Template.JobNamespace != nil {
		out.Spec.Template.JobNamespace = new(string)
		*out.Spec.Template.JobNamespace = *in.Spec.Template.JobNamespace
	}
	if in.Spec.Template.ServiceAccountName != nil {
		out.Spec.Template.ServiceAccountName = new(string)
		*out.Spec.Template.ServiceAccountName = *in.Spec.Template.ServiceAccountName
	}
	if in.Spec.Template.Image != nil {
		out.Spec.Template.Image = new(string)
		*out.Spec.Template.Image = *in.Spec.Template.Image
	}
	if in.Spec.Template.Args != nil {
		out.Spec.Template.Args = append([]string{}, in.Spec.Template.Args...)
	}
	if in.Spec.Template.Cleanup != nil {
		out.Spec.Template.Cleanup = new(bool)
		*out.Spec.Template.Cleanup = *in.Spec.Template.Cleanup
	}
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ZapScheduledScan) DeepCopy() *ZapScheduledScan {
	if in == nil {
		return nil
	}
	out := new(ZapScheduledScan)
	in.DeepCopyInto(out)
	return out
}

func (in *ZapScheduledScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZapScheduledScanList) DeepCopyInto(out *ZapScheduledScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ZapScheduledScan, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *ZapScheduledScanList) DeepCopy() *ZapScheduledScanList {
	if in == nil {
		return nil
	}
	out := new(ZapScheduledScanList)
	in.DeepCopyInto(out)
	return out
}

func (in *ZapScheduledScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZapScheduledScanStatus) DeepCopyInto(out *ZapScheduledScanStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		out.LastScheduleTime = in.LastScheduleTime.DeepCopy()
	}
	if in.Active != nil {
		out.Active = append([]string{}, in.Active...)
	}
}

func (in *ZapScheduledScanStatus) DeepCopy() *ZapScheduledScanStatus {
	if in == nil {
		return nil
	}
	out := new(ZapScheduledScanStatus)
	in.DeepCopyInto(out)
	return out
}
